POST http://localhost:8082/api/data/v1/users/owner
Content-Type: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw==
Accept: */*

{
  "name": "Meghan",
  "email": "meghan@craftchain.tech",
  "phone": "+11298765432",
  "shops": [{"name": "New-York Beauty", "phone": "+1234567789", "ownerName": "Meghan", "activities": ["Make-Up", "Clean-hair", "Afro-hair"]}],
  "address": {
    "city": "New York",
    "country": "USA",
    "state": "Pennsylvania",
    "zip": "25-577-21"
  }
}

###
POST http://localhost:8082/api/data/v1/users/owner
Content-Type: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw==

{
  "name": "Manuel",
  "email": "manuel@craftchain.tech",
  "phone": "+33698765432",
  "shops": [{"name": "Paris Beauty", "phone": "+33134567789", "ownerName": "Manuel", "activities": ["Clean-hair", "Afro-hair"]}],
  "address": {
    "city": "Paris",
    "country": "France",
    "state": "Paris",
    "zip": "75000"
  }
}

###
POST http://localhost:8082/api/data/v1/shops
Content-Type: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw==

{
  "name": "New-York Beauty",
  "phone": "+1234567789",
  "ownerName": "Meghan",
  "activities": ["Make-Up", "Clean-hair", "Afro-hair"],
  "address": {
    "city": "New York",
    "country": "USA",
    "state": "Pennsylvania",
    "zip": "24-566-20"
  }
}

###
POST http://localhost:8082/api/data/v1/shops
Content-Type: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw==

{
  "name": "Paris Beauty",
  "phone": "+33234567789",
  "ownerName": "Manuel",
  "activities": ["Clean-hair", "Afro-hair"],
  "address": {
    "city": "Paris",
    "country": "France",
    "state": "Paris",
    "zip": "75000"
  }
}

###
GET http://localhost:8082/api/data/v1/shops
Accept: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw==

###

###
POST http://localhost:8082/api/data/v1/users/client
Content-Type: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw

{
  "name": "Enzo",
  "email": "enzo@craftchain.tech",
  "phone": "+330198765432",
  "shops": [{"name": "New-York Beauty", "phone": "+1234567789", "ownerName": "Meghan", "activities": ["Make-Up", "Clean-hair", "Afro-hair"]}]
}

###
POST http://localhost:8082/api/data/v1/users/client
Content-Type: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw

{
  "name": "Clara",
  "email": "clara@craftchain.tech",
  "phone": "+330711165432",
  "shops": [{"name": "Paris Beauty", "phone": "+1234567789", "ownerName": "Manuel", "activities": ["Make-Up", "Clean-hair", "Afro-hair"]}]
}

###
GET http://localhost:8082/api/data/v1/users/client
Accept: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw

###
POST http://localhost:8082/api/data/v1/users/employee
Content-Type: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw

{
  "name": "Muriel",
  "email": "muriel@craftchain.tech",
  "phone": "+390123476589",
  "shops": [{"name": "New-York Beauty", "phone": "+1234567789", "ownerName": "Meghan", "activities": ["Make-Up", "Clean-hair", "Afro-hair"]}]
}

###
GET http://localhost:8082/api/data/v1/users/employee
Accept: application/json
Authorization: Basic ZGV2b3BzOmRldm9wcw

###