spring:
  application:
    name: beauty-shop
  data:
    mongodb:
      database: ${spring.application.name}
      username: mongo
      password: mongo
      authentication-database: admin
      host: ${MONGO_HOST} #mandatory to connect on db container

server:
  servlet:
    context-path: /api
  port: 8080

logging:
  file:
    name: ./logs/${spring.application.name}.log