spring:
  application:
    name: beauty-shop
  data:
    mongodb:
      database: ${spring.application.name}
      username: mongo
      password: mongo
      authentication-database: admin
server:
  servlet:
    context-path: /api
logging:
  file:
    name: ./logs/${spring.application.name}.log