spring:
  application:
    name: beauty-shop
  data:
    mongodb:
      database: ${spring.application.name}
      username: mongo #must be comment in localhost
      password: mongo #must be comment in localhost
      authentication-database: admin #must be comment in localhost
      host: ${MONGO_HOST} #mandatory to connect on db container / must be comment in localhost

server:
  servlet:
    context-path: /api
  port: 8080

logging:
  file:
    name: ./logs/${spring.application.name}.log